version: '3.8'

services:
  # VSCode Server - Full IDE
  code-server:
    image: codercom/code-server:latest
    container_name: crowe-ide
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD:-CroweLogic2025}
      - SUDO_PASSWORD=${SUDO_PASSWORD:-CroweAdmin}
      - DEFAULT_WORKSPACE=/workspace
      - VSCODE_PROXY_URI=${VSCODE_PROXY_URI:-https://croweos.com}
    volumes:
      - ./workspace:/workspace
      - ./config:/home/coder/.config
      - ./extensions:/home/coder/.local/share/code-server/extensions
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
      - "3000:3000"  # For Next.js dev server
      - "5173:5173"  # For Vite
    networks:
      - crowe-network
    restart: unless-stopped
    command: |
      --auth password
      --port 8080
      --proxy-domain croweos.com
      --disable-telemetry
      --user-data-dir /home/coder/.config/data
      --extensions-dir /home/coder/.local/share/code-server/extensions
      --install-extension ms-python.python
      --install-extension dbaeumer.vscode-eslint
      --install-extension esbenp.prettier-vscode
      --install-extension ms-azuretools.vscode-docker
      --install-extension GitHub.copilot
      --install-extension anthropic.claude-vscode

  # Terminal Container with full Linux environment
  terminal:
    image: node:20-alpine
    container_name: crowe-terminal
    working_dir: /workspace
    volumes:
      - ./workspace:/workspace
      - node_modules:/workspace/node_modules
    environment:
      - NODE_ENV=development
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: /bin/sh -c "apk add --no-cache git python3 make g++ && tail -f /dev/null"
    networks:
      - crowe-network
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: crowe-db
    environment:
      - POSTGRES_USER=crowe
      - POSTGRES_PASSWORD=${DB_PASSWORD:-CroweDB2025}
      - POSTGRES_DB=crowe_platform
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - crowe-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: crowe-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - crowe-network
    restart: unless-stopped

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: crowe-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - code-server
    networks:
      - crowe-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  node_modules:

networks:
  crowe-network:
    driver: bridge