[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
name = "web"
port = 3000

[services.web]
domains = ["crowecode.com", "www.crowecode.com"]

[[services]]
name = "websocket"
port = 8080

[services.websocket]
domains = ["ws.crowecode.com"]