{% set name = "mycelium-ei-lang" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: YOUR_SHA256_HERE  # Will be updated on build

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mycelium = mycelium_ei.cli:main

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.8
    - numpy >=1.20
    - pandas >=1.3
    - scikit-learn >=1.0
    - matplotlib >=3.4
    - networkx >=2.6
    - biopython >=1.79
    - qiskit >=0.39  # [not win]

test:
  imports:
    - mycelium_ei
  commands:
    - mycelium --help
    - python -m mycelium_ei --version

about:
  home: https://github.com/MichaelCrowe11/pulsar-lang
  license: Proprietary
  license_family: Proprietary
  license_file: LICENSE
  summary: Bio-inspired programming language with quantum computing integration
  description: |
    Mycelium-EI-Lang is a revolutionary programming language that combines
    biological computing paradigms with quantum computing capabilities.
    Features include genetic algorithms, swarm intelligence, neural networks,
    and environmental cultivation systems.
  doc_url: https://mycelium-ei-lang.readthedocs.io
  dev_url: https://github.com/MichaelCrowe11/pulsar-lang

extra:
  recipe-maintainers:
    - MichaelCrowe11