# Google Cloud Build configuration for Crowe Logic Platform
# This builds and deploys to Cloud Run and optionally GKE

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crowe-logic-platform:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/crowe-logic-platform:latest'
      - '.'
    timeout: '1200s'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/crowe-logic-platform'

  # Step 3: Run database migrations
  - name: 'gcr.io/$PROJECT_ID/crowe-logic-platform:$COMMIT_SHA'
    entrypoint: 'npx'
    args:
      - 'prisma'
      - 'migrate'
      - 'deploy'
    env:
      - 'DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${_INSTANCE_CONNECTION_NAME}'
    secretEnv: ['DB_PASSWORD']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'crowe-logic-platform'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crowe-logic-platform:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_INSTANCE_CONNECTION_NAME}'
      - '--set-env-vars'
      - |
        NODE_ENV=production,
        GCP_PROJECT_ID=$PROJECT_ID,
        GCP_LOCATION=${_REGION},
        DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@localhost/${_DB_NAME}?host=/cloudsql/${_INSTANCE_CONNECTION_NAME},
        REDIS_URL=redis://${_REDIS_HOST}:6379,
        NEXT_PUBLIC_APP_URL=https://crowe-logic-platform-${_REGION}-uc.a.run.app
      - '--set-secrets'
      - |
        JWT_SECRET=jwt-secret:latest,
        NEXTAUTH_SECRET=nextauth-secret:latest,
        GOOGLE_APPLICATION_CREDENTIALS=vertex-ai-credentials:latest
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '100'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '1000'

  # Step 5: Deploy to GKE (optional)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'set'
      - 'image'
      - 'deployment/crowe-logic-platform'
      - 'crowe-logic-platform=gcr.io/$PROJECT_ID/crowe-logic-platform:$COMMIT_SHA'
      - '--namespace'
      - 'production'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=${_REGION}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}'

# Substitution variables
substitutions:
  _REGION: us-central1
  _GKE_CLUSTER: crowe-logic-cluster
  _INSTANCE_CONNECTION_NAME: dulcet-nucleus-450804-a3:us-central1:crowe-db
  _DB_NAME: crowe_platform
  _DB_USER: crowe_admin
  _REDIS_HOST: 10.0.0.3
  _PROJECT_ID: dulcet-nucleus-450804-a3

# Build configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
# Secrets from Secret Manager
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/db-password/versions/latest
      env: 'DB_PASSWORD'

# Timeout for the entire build
timeout: '2400s'
